#input values
clip_len : 16
directory : "optical flow video and original video dataset directory of compressed numpy array
            [directory->train, color_train, val, color_val -> class_name -> videos] where color_train and color_val are 
            numpy array of optical flow videos "
gpu : [1]
fast_dev_run : False


#config
num_classes : 13
layer_sizes : [2, 2, 2, 2]
precision : 16
crop_size : 112
frame_offset : 1

#To update the resize height and resize width, need to compress the dataset again
resize_height : 128
resize_width : 172


#hyperparameter
epoch : 1000
optimizer : "SGD"
lr_rate : 0.01
weight_decay : 0.0001
batch_size : 32
num_worker : 32


#Early stopping
early_stopping : False
patience : 20

#logging folder
tensorboard_folder_name : "two_stream"